// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzn-XycR20_eHh6xUYSAOafD3qtLry1JA',
    appId: '1:831808483289:android:6522c178eb3269d2dcf3c8',
    messagingSenderId: '831808483289',
    projectId: 'benha-offers',
    storageBucket: 'benha-offers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD7CfJNODJa_fyV10GFpwLUWhZKdf473A',
    appId: '1:831808483289:ios:4ca9dd3effca81b9dcf3c8',
    messagingSenderId: '831808483289',
    projectId: 'benha-offers',
    storageBucket: 'benha-offers.appspot.com',
    androidClientId:
        '831808483289-18ibu20eu09qqts3eq791r2rk9rrlnq8.apps.googleusercontent.com',
    iosClientId:
        '831808483289-g5k7dhkrpv63nhkgfo2ivjnsd6lkl4go.apps.googleusercontent.com',
    iosBundleId: 'com.deve.benhaoffers',
  );
}
