// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMoF7bolf5G3bhLxe1EIzF_7k2cRpn7i0',
    appId: '1:223851828128:android:935655f1e261374e200ac5',
    messagingSenderId: '223851828128',
    projectId: 'bsoraa-55c9d',
    storageBucket: 'bsoraa-55c9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9l42179EM8sZ1IRQZjByT8nSoTtNtT34',
    appId: '1:223851828128:ios:4eeffdcaf89570ae200ac5',
    messagingSenderId: '223851828128',
    projectId: 'bsoraa-55c9d',
    storageBucket: 'bsoraa-55c9d.appspot.com',
    androidClientId:
        '223851828128-rpchfe6mkbi0f65dn97dflavqmsdauvb.apps.googleusercontent.com',
    iosClientId:
        '223851828128-rpchfe6mkbi0f65dn97dflavqmsdauvb.apps.googleusercontent.com',
    iosBundleId: 'com.deve.benhaoffers',
  );
}
